# Generated by Django 4.1.1 on 2024-02-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='classification',
            field=models.CharField(default='', max_length=20),
        ),
    ]
