# Generated by Django 4.1.1 on 2024-02-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='censored_value',
            field=models.TextField(blank=True),
        ),
    ]
